[package]
name = "sandbox-server"
version = "0.1.0"
edition = "2021"

[dependencies]
# server
actix-web = "4.0.0-beta.10"
actix-rt = "2.4.0"
# client wasm
wasm-bindgen = "0.2"

[[bin]]
name = "strattera-example-server"

[[bin]]
name = "strattera-example-client"
