[package]
name = "prpr-server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-files = "0.6.0-beta.6"
actix-http = "3.0.0-beta.9"
actix-multipart = "0.4.0-beta.5"
actix-session = "0.5.0-beta.2"
actix-web = "4.0.0-beta.8"
prpr = { path = "../prpr" }
