[package]
name = "prpr-client"
version = "0.1.0"
edition = "2021"

[dependencies]
wasm-bindgen = "0.2.63"
prpr-anywhere = { path = "../anywhere" }

[dependencies.web-sys]
version = "0.3.55"
features = [
  'Document',
  'Element',
  'Node',
  'Text',
  'Window',
]
